name: SonarQube
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Les clones superficiels doivent être désactivés pour une meilleure pertinence de l'analyse
      - name: Build and run Docker container
        run: |
          docker build -t my-app .
          docker run -d --name my-app-container my-app
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin' # D'autres options de distribution sont disponibles.
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Nécessaire pour obtenir les informations sur les PR, le cas échéant
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          docker exec my-app-container mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=lbaudroit_gestion-tournee-commercial-backend
      - name: Stop and remove Docker container
        run: |
          docker stop my-app-container
          docker rm my-app-container
