name: Build JAR and Docker Image

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build JAR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: 'temurin'
          
      - name: Docker Setup Compose
        uses: docker/setup-compose-action@v1.0.0

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Start Docker Compose
        run: docker compose -f compose.yaml up -d

      - name: Build with Maven
        run: mvn clean package -Dskiptest

      - name: Rename JAR file
        run: mv /home/runner/work/gestion-tournee-commercial-backend/gestion-tournee-commercial-backend/target/backendtourneecommercial-0.0.1-SNAPSHOT.jar /home/runner/work/gestion-tournee-commercial-backend/gestion-tournee-commercial-backend/target/backendtourneecommercial.jar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: tournee-commercial-jar
          path: /home/runner/work/gestion-tournee-commercial-backend/gestion-tournee-commercial-backend/target/backendtourneecommercial.jar

  dockerize:
    name: Build Docker Image
    runs-on: ubuntu-latest # Or use a matrix of runners if you have ARM runners
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64] # Build for BOTH
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: tournee-commercial-jar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:v0.11.2-rootless
  
      - name: Build Docker image for ${{ matrix.platform }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: deployment/Dockerfile
          platforms: ${{ matrix.platform }} # Crucial: Build for the specific platform
          push: false # No push to registry
          tags: tournee-commercial:${{ matrix.platform }}-0.0.1 # Important: Platform-specific tags
  
      - name: Save Docker image to a tar file
        run: docker save -o tournee-commercial-${{ matrix.platform }}.tar tournee-commercial:${{ matrix.platform }}-0.0.1
  
      - name: Upload Docker artifact
        uses: actions/upload-artifact@v4
        with:
          name: tournee-commercial-docker-${{ matrix.platform }} # Platform-specific artifact names
          path: tournee-commercial-${{ matrix.platform }}.tar
