name: Build JAR and Docker Image

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build JAR and Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean package

      - name: Docker Setup Compose
        uses: docker/setup-compose-action@v1.0.0

      - name: Build and push Docker image
        run: |
          docker build -t tournee-commercial:0.0.1 .

      - name: Save Docker image to file
        run: docker save tournee-commercial:0.0.1 -o tournee-commercial.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: tournee-commercial-image
          path: tournee-commercial.tar
