name: Build JAR and Docker Image

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build JAR and Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: 'temurin'
          
      - name: Docker Setup Compose
        uses: docker/setup-compose-action@v1.0.0

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Start Docker Compose
        run: docker compose -f compose.yaml up -d

      - name: Build with Maven
        run: mvn clean package

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: tournee-commercial-jar
          path: /home/runner/work/gestion-tournee-commercial-backend/gestion-tournee-commercial-backend/target/backendtourneecommercial-0.0.1-SNAPSHOT.jar.original
